### ISSUE TITLE
How to run experiment

### ISSUE THREAD

**Issue by klangner** [JuliaReinforcementLearning/ReinforcementLearningZoo.jl#104]
Sorry if this is trivial. But how can I run experiment?
I tried to:
  1. clone this repo
  2. Start julia inside this repo and activate the project
  3. Then I try to run experiment with: 
```
run(E`JuliaRL_BasicDQN_CartPole`)
```
But I get:
```
ERROR: LoadError: UndefVarError: @E_cmd not defined
```
What am I missing?

**Comment by findmyway** [comment]
Oops, sorry that I forgot to mention it clearly in README. You need to have `ReinforcementLearningEnvironments` installed first. And `using ReinforcementLearningEnvironments`.

A general tip, you can check out the test file for some more detailed usages.

https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/22d500f51964caa482879a174c2afce9fd5e4fb0/test/runtests.jl#L5-L5
