### ISSUE TITLE
Mean Actor-Critic

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearningZoo.jl#11]
https://arxiv.org/pdf/1709.00503.pdf

**Comment by RajGhugare19** [comment]
@findmyway Can I take up this issue as a starting point?

**Comment by RajGhugare19** [comment]
@findmyway I have some doubts
1) I don't understand how gains are calculated in A2C. Are they just the discounted reward to go? let's say the rewards is a matrix of (nthreads, m). Where m is the update freq. So, the gains would be an array of shape (nthreads*m,). 
2) In A2C, shouldn't the updates lengths be equal to the length of the most recent trajectory rather than a fixed update freq?

**Comment by findmyway** [comment]
1. Yes

The related code is here:

https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/2e5a43f4af3bce933c4a617952276706b04785b9/src/algorithms/policy_gradient/A2C.jl#L67-L74

But note that the size is `(m, nthreads)`, not `(nthreads, m)` here.

2. In theory, the update frequency can be a different value of the length of the trajectory. But  here for simplicity, the update frequency is set to be the same with the length of the trajectory. So yes you're right here.

https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/2e5a43f4af3bce933c4a617952276706b04785b9/src/algorithms/policy_gradient/A2C.jl#L45

https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/2e5a43f4af3bce933c4a617952276706b04785b9/src/algorithms/policy_gradient/A2C.jl#L112-L115

**Comment by RajGhugare19** [comment]
I have implemented MAC, The agent is learning but isn't getting a constant reward of 200, rather it is getting noisy rewards. I tried hyperparam tuning but the performance isn't like A2C. The agent is getting an average return of 150

**Comment by findmyway** [comment]
Average reward of 150 is not so bad, though slightly lower the the reported value. Could you create a pr and see if there's any bug?

**Comment by RajGhugare19** [comment]
Yeah I am checking for bugs, I am positive that there aren't any (because the agent is learning). I'll check once more and create a pr by tonight

**Comment by RajGhugare19** [comment]
I have made the pr (sorry for the delay :p)
